services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bitnami/php-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      XDEBUG_CONFIG: remote_host=host.docker.internal
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - wce

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - wce

  redis:
    image: redis:8-alpine
    privileged: true
    networks:
      - wce
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

#Docker Networks
networks:
    wce:
        driver: bridge

#Docker Volumes
volumes:
  redis-data:
    driver: local
